#!/bin/bash

echo " Check Server "

APACHE=$(/usr/local/apache/bin/apachectl -v|head -1|cut -d: -f2|awk '{print $1}'|cut -d/ -f2)
PHP=$(/usr/local/bin/php -v |head -1|awk '{print $2}')
PERL=$(/usr/bin/perl -v|head -n2|awk '{print $4}'|sed -e'/^$/d')
MYSQL=$(/usr/bin/mysql --version|awk '{print $5}'|sed -e 's/,//g')

CPANEL=$(/usr/local/cpanel/cpanel -V|awk '{print $1}')
#GD=$(/usr/local/bin/php -i|grep GD| grep '('|awk '{print $5}'|sed -e 's/(//g')
PERL=$(/usr/bin/perl -v|head -2|sed -e'/^$/d'|awk '{print $4}'|sed -e 's/v//g')
IONCUBE=$(/usr/local/bin/php -i|grep Cube|awk '{print $6}'|sed -e 's/v//g'|cut -d, -f1)
GNUPG=$(/usr/bin/gpg2 --version|head -1|awk '{print $3}')
#GD=$(rpm -qa|grep gd-|egrep -v "gd-devel|gd-progs"| cut -d '-' -f2)
#OPENSSL=$(/usr/bin/openssl version|awk '{print $2}'|cut -d '-' -f1|sed -e 's/e//g')
RUBY=$(/usr/bin/ruby --version|awk '{print $2}')
CURL=$(/usr/bin/curl --version|head -1|awk '{print $2}')
PERL=$(/usr/bin/perl -version| head -2|sed -e'/^$/d'|awk '{print $4}'|sed -e 's/v//g')
PYTHON=$(rpm -qa|grep python-|egrep -v "python-[a-zA-Z]|rpm|newt|lib"|cut -d '-' -f2)

#IMAGEMAGICK=$(/usr/local/bin/php -i|grep image|awk '{print $5}'|head -1|cut -d '-' -f1)
#IMAGICKMOD=$(/usr/local/bin/php -i | grep "imagick module version" | awk '{print $5}')
#GHOSTSCRIPT=$(/usr/bin/ghostscript --version)

RSYNC=$(/usr/bin/rsync --version|head -1|awk '{print $3}')

ROUDCUBE=$(cat /var/cpanel/roundcube/version)
SQUIREMAIL=$(cat /var/cpanel/squirrelmail/version)
HORDE=$(cat /var/cpanel/horde/version)

echo -e "
Apache:\t\t$APACHE
PHP:\t\t$PHP
MySQL:\t\t$MYSQL
----------------------
cPanel:\t\t$CPANEL
----------------------
#GD LIB:\t\t$GD
Perl:\t\t$PERL
IonCube:\t$IONCUBE
gnuPG:\t\t$GNUPG
----------------------
#GD:\t\t$GD
#OpenSSL:\t$OPENSSL
ROR:\t\t$RUBY
Curl:\t\t$CURL
Perl:\t\t$PERL
Python:\t\t$PYTHON
---------------------
#ImageMagick\t\t$IMAGEMAGICK\tImageMagick PHP Mod:\t\t$IMAGICKMOD
#GhostScript:\t$GHOSTSCRIPT

rsync:\t\t$RSYNC
RoudCube:\t$ROUDCUBE\tSquireMail:\t$SQUIREMAIL\tHorde:\t$HORDE "
