version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "sinesiobittencourt/shell_script"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  test:
    title: "Running test"
    type: "freestyle"
    image: "ubuntu:latest"
    working_directory: "${{clone}}" 
    commands:
      - "ls -la"
      - "chmod 750 *"
      - "ls -la"     
    stage: "test"
