#!/bin/bash

##################################################################
# Author       : Sinesio Bittencourt
# Email        : contato@sinesio.com.br
# Info         : 
# Version      : 0.1 ( beta )
# Project      : http://git.sinesio.com.br
##################################################################

## BASHCSS
verm='\E[0;31m'   # Red
verd='\E[0;32m'   # Green
amar='\E[0;33m'   # Yellow
bold='\033[37;4;1m' #BOLD
und='\033[37;4m'
rese=$(tput sgr0) # No color.
OK="${verd}[OK]${rese}";                                                                                                                                                                                                                                                       
ATT="${amar}[!]${rese}";                                                                                                                                                                                                                                                       
FAIL="${verm}[!]${rese}"; 

VERSAO="0.1b"
#limpar tela
#clear

printf "
# Author       : Sinesio Bittencourt
# Email        : contato@sinesio.com.br
# Info         : 
# Version      : v$VERSAO ( beta )
       "
echo -e "\n[!] - Bem vindo Gator.\n"
read -p "Informe o DOMINIO a ser REMOVIDO: "		DOMINIO
read -p "Informe o DOMINIO PRINCIPAL(owner) da conta: "		OWNER
echo -e "\n"



# CHECA SE OS VALORES FORAM INSERIDOS CORREETAMENTE
if [[ -z $DOMINIO ]]
then
       	echo -e "${FAIL} - Nenhum valor pode ficar em branco, por favor tente novamente."
	exit
else
	#printf \n${OK} "- Execultando comando" ${rese}\n\n
	printf "\n${OK} - Verificando o DOMINIO\n"
	printf "\n${OK} - Execultando comando\n\n" 
	
	/scripts/whoowns $DOMINIO\n
	#echo $DOMINIO
	/scripts/killdns $DOMINIO\n
	/scripts/killvhost $DOMINIO\n
	/scripts/cleandns $DOMINIO\n
	
	sleep 3
	printf "\n${OK} - mpando cache do servidor\n\n" 
	
	/scripts/updateuserdomains; 
	/scripts/update_db_cache;
	sleep 2
echo -e "Domínio >>> "${verd}$DOMINIO${rese}" <<< removido com SUCESSO!"
	/root/bin/ui $OWNER\n
echo -e "Domínio >>> "${verd}$OWNER${rese}" <<< Verificando se o domínio foi removido o ADD!"

fi
